import argparse
from datetime import datetime, timezone
from pathlib import Path
import math

from fastf1.ergast import Ergast


def sql_escape(value: str) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def to_int_or_none(x):
    # pandas/np NaN -> float and x != x is True
    if x is None:
        return None
    if isinstance(x, float) and math.isnan(x):
        return None
    try:
        # sometimes it's '1' (string) or 1.0 (float)
        return int(float(x))
    except (ValueError, TypeError):
        return None


def to_float_or_none(x):
    if x is None:
        return None
    if isinstance(x, float) and math.isnan(x):
        return None
    try:
        return float(x)
    except (ValueError, TypeError):
        return None


def generate_sql(season_year: int, mode: str) -> str:
    ergast = Ergast()
    standings = ergast.get_driver_standings(season=season_year)
    df = standings.content[0]

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S%z")

    lines = []
    lines.append("-- Generated by generate_driver_standings_sql.py")
    lines.append(f"-- season_year: {season_year}")
    lines.append(f"-- generated_at_utc: {now_utc}")
    lines.append("BEGIN;")
    lines.append("")

    if mode == "delete_insert":
        lines.append(f"DELETE FROM driver_standings WHERE season_year = {season_year};")
        lines.append("")

    skipped = 0

    for _, row in df.iterrows():
        driver_name = f"{row.get('givenName', '')} {row.get('familyName', '')}".strip()
        if not driver_name:
            skipped += 1
            continue

        constructor_names = row.get("constructorNames", [])
        team_name = constructor_names[0] if constructor_names else None

        points = to_float_or_none(row.get("points"))
        position = to_int_or_none(row.get("position"))

        # If either key numeric field is missing, skip row
        if points is None or position is None:
            skipped += 1
            continue

        driver_sql = sql_escape(driver_name)
        team_sql = sql_escape(team_name)
        last_updated_sql = sql_escape(now_utc)

        if mode == "upsert":
            stmt = f"""
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES ({season_year}, {driver_sql}, {team_sql}, {points}, {position}, {last_updated_sql}::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
""".strip()
        else:
            stmt = f"""
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES ({season_year}, {driver_sql}, {team_sql}, {points}, {position}, {last_updated_sql}::timestamptz);
""".strip()

        lines.append(stmt)

    lines.append("")
    lines.append(f"-- skipped_rows_due_to_missing_values: {skipped}")
    lines.append("COMMIT;")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--year", type=int, required=True)
    parser.add_argument("--mode", choices=["upsert", "delete_insert"], default="upsert")
    parser.add_argument("--out", type=str, default=None)
    args = parser.parse_args()

    sql = generate_sql(args.year, args.mode)

    out_path = Path(args.out) if args.out else Path(f"driver_standings_{args.year}_{args.mode}.sql")
    out_path.write_text(sql, encoding="utf-8")
    print(f"✅ Wrote SQL to: {out_path.resolve()}")


if __name__ == "__main__":
    com