-- Generated by generate_driver_standings_sql.py
-- season_year: 2002
-- generated_at_utc: 2026-01-14 14:04:06+0000
BEGIN;

INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Michael Schumacher', 'Ferrari', 144.0, 1, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Rubens Barrichello', 'Ferrari', 77.0, 2, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Juan Pablo Montoya', 'Williams', 50.0, 3, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Ralf Schumacher', 'Williams', 42.0, 4, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'David Coulthard', 'McLaren', 41.0, 5, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Kimi Räikkönen', 'McLaren', 24.0, 6, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Jenson Button', 'Renault', 14.0, 7, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Jarno Trulli', 'Renault', 9.0, 8, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Eddie Irvine', 'Jaguar', 8.0, 9, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Nick Heidfeld', 'Sauber', 7.0, 10, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Giancarlo Fisichella', 'Jordan', 7.0, 11, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Jacques Villeneuve', 'BAR', 4.0, 12, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Felipe Massa', 'Sauber', 4.0, 13, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Olivier Panis', 'BAR', 3.0, 14, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Takuma Sato', 'Jordan', 2.0, 15, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Mark Webber', 'Minardi', 2.0, 16, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Mika Salo', 'Toyota', 2.0, 17, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Heinz-Harald Frentzen', 'Arrows', 2.0, 18, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Allan McNish', 'Toyota', 0.0, 19, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Alex Yoong', 'Minardi', 0.0, 20, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Pedro de la Rosa', 'Jaguar', 0.0, 21, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2002, 'Enrique Bernoldi', 'Arrows', 0.0, 22, '2026-01-14 14:04:06+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;

-- skipped_rows_due_to_missing_values: 1
COMMIT;
