-- Generated by generate_driver_standings_sql.py
-- season_year: 1951
-- generated_at_utc: 2026-01-14 14:14:32+0000
BEGIN;

INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Juan Fangio', 'Alfa Romeo', 31.0, 1, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Alberto Ascari', 'Ferrari', 25.0, 2, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'José Froilán González', 'Talbot-Lago', 24.0, 3, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Nino Farina', 'Alfa Romeo', 19.0, 4, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Luigi Villoresi', 'Ferrari', 15.0, 5, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Piero Taruffi', 'Ferrari', 10.0, 6, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Lee Wallard', 'Kurtis Kraft', 9.0, 7, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Felice Bonetto', 'Alfa Romeo', 7.0, 8, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Mike Nazaruk', 'Kurtis Kraft', 6.0, 9, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Reg Parnell', 'Ferrari', 5.0, 10, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Luigi Fagioli', 'Alfa Romeo', 4.0, 11, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Consalvo Sanesi', 'Alfa Romeo', 3.0, 12, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Louis Rosier', 'Talbot-Lago', 3.0, 13, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Andy Linden', 'Sherman', 3.0, 14, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Jack McGrath', 'Kurtis Kraft', 2.0, 15, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Manny Ayulo', 'Kurtis Kraft', 2.0, 16, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Toulo de Graffenried', 'Alfa Romeo', 2.0, 17, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Yves Cabantous', 'Talbot-Lago', 2.0, 18, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1951, 'Bobby Ball', 'Schroeder', 2.0, 19, '2026-01-14 14:14:32+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;

-- skipped_rows_due_to_missing_values: 11
COMMIT;
