-- Generated by generate_driver_standings_sql.py
-- season_year: 1990
-- generated_at_utc: 2026-01-14 14:09:58+0000
BEGIN;

INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Ayrton Senna', 'McLaren', 78.0, 1, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Alain Prost', 'Ferrari', 71.0, 2, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Nelson Piquet', 'Benetton', 43.0, 3, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Gerhard Berger', 'McLaren', 43.0, 4, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Nigel Mansell', 'Ferrari', 37.0, 5, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Thierry Boutsen', 'Williams', 34.0, 6, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Riccardo Patrese', 'Williams', 23.0, 7, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Alessandro Nannini', 'Benetton', 21.0, 8, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Jean Alesi', 'Tyrrell', 13.0, 9, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Ivan Capelli', 'Leyton House', 6.0, 10, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Roberto Moreno', 'Euro Brun', 6.0, 11, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Aguri Suzuki', 'Larrousse', 6.0, 12, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Éric Bernard', 'Larrousse', 5.0, 13, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Derek Warwick', 'Team Lotus', 3.0, 14, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Satoru Nakajima', 'Tyrrell', 3.0, 15, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Alex Caffi', 'Arrows', 2.0, 16, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Stefano Modena', 'Brabham', 2.0, 17, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (1990, 'Maurício Gugelmin', 'Leyton House', 1.0, 18, '2026-01-14 14:09:58+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;

-- skipped_rows_due_to_missing_values: 12
COMMIT;
