-- Generated by generate_driver_standings_sql.py
-- season_year: 2007
-- generated_at_utc: 2026-01-14 14:03:43+0000
BEGIN;

INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Kimi Räikkönen', 'Ferrari', 110.0, 1, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Lewis Hamilton', 'McLaren', 109.0, 2, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Fernando Alonso', 'McLaren', 109.0, 3, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Felipe Massa', 'Ferrari', 94.0, 4, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Nick Heidfeld', 'BMW Sauber', 61.0, 5, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Robert Kubica', 'BMW Sauber', 39.0, 6, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Heikki Kovalainen', 'Renault', 30.0, 7, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Giancarlo Fisichella', 'Renault', 21.0, 8, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Nico Rosberg', 'Williams', 20.0, 9, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'David Coulthard', 'Red Bull', 14.0, 10, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Alexander Wurz', 'Williams', 13.0, 11, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Mark Webber', 'Red Bull', 10.0, 12, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Jarno Trulli', 'Toyota', 8.0, 13, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Sebastian Vettel', 'BMW Sauber', 6.0, 14, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Jenson Button', 'Honda', 6.0, 15, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Ralf Schumacher', 'Toyota', 5.0, 16, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Takuma Sato', 'Super Aguri', 4.0, 17, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Vitantonio Liuzzi', 'Toro Rosso', 3.0, 18, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Adrian Sutil', 'Spyker', 1.0, 19, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Rubens Barrichello', 'Honda', 0.0, 20, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Scott Speed', 'Toro Rosso', 0.0, 21, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Kazuki Nakajima', 'Williams', 0.0, 22, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Anthony Davidson', 'Super Aguri', 0.0, 23, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Sakon Yamamoto', 'Spyker', 0.0, 24, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2007, 'Christijan Albers', 'Spyker', 0.0, 25, '2026-01-14 14:03:43+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;

-- skipped_rows_due_to_missing_values: 1
COMMIT;
