-- Generated by generate_driver_standings_sql.py
-- season_year: 2014
-- generated_at_utc: 2026-01-14 13:52:05+0000
BEGIN;

INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Lewis Hamilton', 'Mercedes', 384.0, 1, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Nico Rosberg', 'Mercedes', 317.0, 2, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Daniel Ricciardo', 'Red Bull', 238.0, 3, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Valtteri Bottas', 'Williams', 186.0, 4, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Sebastian Vettel', 'Red Bull', 167.0, 5, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Fernando Alonso', 'Ferrari', 161.0, 6, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Felipe Massa', 'Williams', 134.0, 7, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Jenson Button', 'McLaren', 126.0, 8, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Nico Hülkenberg', 'Force India', 96.0, 9, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Sergio Pérez', 'Force India', 59.0, 10, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Kevin Magnussen', 'McLaren', 55.0, 11, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Kimi Räikkönen', 'Ferrari', 55.0, 12, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Jean-Éric Vergne', 'Toro Rosso', 22.0, 13, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Romain Grosjean', 'Lotus F1', 8.0, 14, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Daniil Kvyat', 'Toro Rosso', 8.0, 15, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Pastor Maldonado', 'Lotus F1', 2.0, 16, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Jules Bianchi', 'Marussia', 2.0, 17, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Adrian Sutil', 'Sauber', 0.0, 18, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Marcus Ericsson', 'Caterham', 0.0, 19, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Esteban Gutiérrez', 'Sauber', 0.0, 20, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Max Chilton', 'Marussia', 0.0, 21, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Kamui Kobayashi', 'Caterham', 0.0, 22, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;
INSERT INTO driver_standings (season_year, driver, team, points, position, last_updated)
VALUES (2014, 'Will Stevens', 'Caterham', 0.0, 23, '2026-01-14 13:52:05+0000'::timestamptz)
ON CONFLICT (season_year, driver)
DO UPDATE SET
  team = EXCLUDED.team,
  points = EXCLUDED.points,
  position = EXCLUDED.position,
  last_updated = EXCLUDED.last_updated;

-- skipped_rows_due_to_missing_values: 1
COMMIT;
