export const GP_ROUNDS = [
  { round: 1,  label: "Australian Grand Prix" },
  { round: 2,  label: "Chinese Grand Prix" },
  { round: 3,  label: "Japanese Grand Prix" },
  { round: 4,  label: "Bahrain Grand Prix" },
  { round: 5,  label: "Saudi Arabian Grand Prix" },
  { round: 6,  label: "Miami Grand Prix" },
  { round: 7,  label: "Canadian Grand Prix" },
  { round: 8,  label: "Monaco Grand Prix" },
  { round: 9,  label: "Spanish Grand Prix (Catalunya)" },
  { round: 10, label: "Austrian Grand Prix" },
  { round: 11, label: "British Grand Prix" },
  { round: 12, label: "Belgian Grand Prix" },
  { round: 13, label: "Hungarian Grand Prix" },
  { round: 14, label: "Dutch Grand Prix" },
  { round: 15, label: "Italian Grand Prix" },
  { round: 16, label: "Spanish Grand Prix (Madrid)" },
  { round: 17, label: "Azerbaijan Grand Prix" },
  { round: 18, label: "Singapore Grand Prix" },
  { round: 19, label: "United States Grand Prix" },
  { round: 20, label: "Mexico City Grand Prix" },
  { round: 21, label: "São Paulo Grand Prix" },
  { round: 22, label: "Las Vegas Grand Prix" },
  { round: 23, label: "Qatar Grand Prix" },
  { round: 24, label: "Abu Dhabi Grand Prix" },
];
